name: navigation
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  home:
    path: ../features/home
  room_detail:
    path: ../features/room_detail
  settings:
    path: ../features/settings
  add_room:
    path: ../features/add_room
  edit_room:
    path: ../features/edit_room
  all_rooms:
    path: ../features/all_rooms
  test_history:
    path: ../features/test_history
  authentication:
    path: ../features/authentication

  auto_route: ^7.8.4

dev_dependencies:
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8